server:
  port: 8080
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7900/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: api-passenger